### ISSUE TITLE
Uncaught Exceptions

### ISSUE THREAD

**Issue by 3zzy** [Exeu/apai-io#130]
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET http://webservices.amazon.co.uk/onca/xml?AWSAccessKeyId=...&AssociateTag=...&Keywords=00AG590%20%22LENOVO%22&Operation=ItemSearch&ResponseGroup=EditorialReview%2CImages%2CItemAttributes%2CBrowseNodes&SearchIndex=All&Service=AWSECommerceService&Timestamp=2016-12-18T19%3A14%3A25Z&Version=2013-08-01&Signature=%2B7sW%2FHhodgm2wl5IEyFYwoVcUi3J%2B9SA%2FRC8v9YD22o%3D` resulted in a `400 Bad Request` response:
<?xml version="1.0"?>
<ItemSearchErrorResponse xmlns="http://ecs.amazonaws.com/doc/2013-08-01/"><Error><Code>AWS.Invalid (truncated...)
 in /var/www/myapp/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /var/www/myapp/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/myapp/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware in /var/www/myapp/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET http://webservices.amazon.co.uk/onca/xml?AWSAccessKeyId=...&AssociateTag=...&Keywords=00AG590%20%22LENOVO%22&Operation=ItemSearch&ResponseGroup=EditorialReview%2CImages%2CItemAttributes%2CBrowseNodes&SearchIndex=All&Service=AWSECommerceService&Timestamp=2016-12-18T19%3A14%3A25Z&Version=2013-08-01&Signature=%2B7sW%2FHhodgm2wl5IEyFYwoVcUi3J%2B9SA%2FRC8v9YD22o%3D` resulted in a `400 Bad Request` response:
<?xml version="1.0"?>
<ItemSearchErrorResponse xmlns="http://ecs.amazonaws.com/doc/2013-08-01/"><Error><Code>AWS.Invalid (truncated...)
 in /var/www/myapp/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /var/www/myapp/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/myapp/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware in /var/www/myapp/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111
```

.. although the same XML is accessible via browser and the error is: 

```
<Errors>
<Error>
<Code>AWS.ECommerceService.NoExactMatches</Code>
<Message>We did not find any matches for your request.</Message>
</Error>
</Errors>
```

**Comment by djeraseit** [comment]
I was getting errors as well and copied the response in the browser, turns out I did not activate product api.
