### ISSUE TITLE
Sometimes can't connect to China webservice

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [Exeu/apai-io#131]
The following error occurs only sometimes, when connecting to webservices.amazon.cn. All other countries work fine.
I'm not sure whether that's misconfiguration or a bug in apai-io...

[30-Dec-2016 09:38:00 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: couldn't connect to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/vicfont/public_html/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /home/vicfont/public_html/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/vicfont/public_html/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/vicfont/public_html/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/vicfont/public_html/myproject/vendo in /home/vicfont/public_html/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

**Comment by JanKrohn-Khalibre** [comment]
Issue is no longer happening. Must have been something on Amazon side...
